### PR TITLE
muta emoje pa graf

### PR DESCRIPTION
**Pull request by jkunimune15**
emoje si mutabli e no fiksabli. sa me vida pandunia.info, me no abla vida bandir; me mon vida harfe ("ID MY BN SG" e al). mon esperanti bandir e panduni bandir rupu ko graf.

gar muta pa graf _svg_, pan ren abla vida bandir sa pan _browser_.

sa sabu `bandir/` loku sa `.gitignore`, me dona novi bandir dokum sa ye:
[bandir.zip](https://github.com/barumau/pandunia/files/4081283/bandir.zip)

### CODE REVIEW

**Comment by barumau** [comment]
problem! ru.svg esa lili. cn.svg e hk.svg no zayu!

**Comment by jkunimune15** [comment]
a! pardon. plus, haitia no sahi. pliza:

[bandir-da-memulu.zip](https://github.com/barumau/pandunia/files/4084310/bandir-da-memulu.zip)

**Comment by jkunimune15** [comment]
a! e peru!
[bandir-da-memulu.zip](https://github.com/barumau/pandunia/files/4084358/bandir-da-memulu.zip)

**Comment by barumau** [comment]
danke!

me plus maxa "emoje" pa leksoliste. ;)

**Pull request merged**
