### PR TITLE
Source layout updated; Esperanto and Spanish contents updated and improved

### PR DESCRIPTION
**Pull request by programandala-net**
Before updating the Esperanto and Spanish contents, I update the source layout of the corresponding English page, i.e. with left justified code with normal length lines, atx-style headings, regular separation between blocks, etc., in order to make editing and comparing versions simpler.

I'm working with three related repos for the first time (my local copy, my remote and the original), and I had some doubts about merging in order to keep everything sync. Please let me know if something is wrong.

### CODE REVIEW

**Comment by barumau** [comment]
I will make a cherry-pick merge from this because there are some issues.

- The /v/ sound is described in Spanish version but Pandunia doesn't have that sound!
- It is said that Pandunia's <h> is not in Spanish but for all intents Pandunia <h> is equal to Spanish <j>.
- There is an unnecessary reference to a book about Esperanto. I prefer that other conlangs are not mentioned in Pandunia lessons. They shall be mentioned only in articles where the explicit intention is to compare Pandunia and other conlangs.

**Comment by barumau** [comment]
I merged these manually somehow...

**Comment by programandala-net** [comment]
>     The /v/ sound is described in Spanish version but Pandunia doesn't have that sound!

I'm sorry about that silly error. Too much inertia while I was editing the sound descriptions...

>     It is said that Pandunia's is not in Spanish but for all intents Pandunia is equal to Spanish .

It seems something is missing from your sentence. Which sound do you mean?

>     There is an unnecessary reference to a book about Esperanto. I prefer that other conlangs are not mentioned in Pandunia lessons. They shall be mentioned only in articles where the explicit intention is to compare Pandunia and other conlangs.

Ok. It makes sense. Since I copied or adapted the detailed sound descriptions and examples from an annex of that book, which is most reliable, and especially written for Spanish speakers, I thought it was fair to add a credit notice. In fact I doubted whether to use an HTML comment or not. Is it fine if I add a hidden HTML comment, in  a shorter form, only as a reference for future editors of the page?

**Comment by barumau** [comment]
I tried to say that Pandunia's h is similar to Spanish j.

HTML style comments are possible. However I hope you can simplify the instructions that so that most Spanish speakers get what sound is described. We should write the instructions for common people. In particular, we can't expect that they would speak a lot of different languages.

**Comment by programandala-net** [comment]
En/Je/On/na 2018-12-21 09:54, Risto Kupsala escribió/skribis/wrote/pas kitaba:

> I tried to say that Pandunia's h is similar to Spanish j.

If I understand clearly, Pandunia's 'h' is [h] (Esperanto's 'h'), while
Spanish' 'j' is [x] (Esperanto's 'ĥ'). Somehow they are similar, as you
say.  Though [h] does not exist in Spanish, it's the "relaxed" sound of
'j' in many occasions.  Why dont't explain this with a bit detail?
Saying it's "similar" would be too vague. Does "similar" mean "stronger"
or "softer" or "longer"?

> I hope you can simplify the instructions that so that most Spanish
> speakers get what sound is described. We should write the instructions
> for common people. 

That is the intention.  But I'll try to shorten and simplify.

> In particular, we can't expect that they would
> speak a lot of different languages.

Of course. On the contrary, examples from several languages are provided
not because people need to speak a lot of languages in order to
understand, but because probably they are familiar with one of those
words, in order to identify a sound that does not exist in Spanish.
When possible, examples from the nearest brother languages (Catalan,
Galician, French and Portuguese) are used.  Besides, a plain description
of the sound is provided.

As said, the revision is not finished. For example, the descriptions of
'h' and 'z' still need a rewording to make them clearer.

-- 
Marcos Cruz
http://programandala.net

**Comment by barumau** [comment]
Both [h] and [x] are accepted ways to pronounce h in Pandunia. They are alternative realizations (i.e. allophones) of the same phoneme. So it is enough to explain that Pandunia h is pronounced like Spanish j and that's that.

Are Spanish speaking people in Latin America familiar with Catalan and Galician?

**Comment by programandala-net** [comment]
En/Je/On/na 2018-12-28 12:09, Risto Kupsala escribió/skribis/wrote/pas
kitaba:

> Both [h] and [x] are accepted ways to pronounce h in Pandunia. They
> are alternative realizations (i.e. allophones) of the same phoneme.

Ok, thanks! That explains the issue. I wasn't aware of allophones in
this case because I saw no mention about them in the English, Spanish
and Esperanto pages, which I use as reference.

The start of the pronunciation sections, showing the IPA equivalents of
the Pandunia alphabet, is very useful, as a concise explanation for
people acquainted with IPA.  What about adding more lines to show all
the allowed alophones (or maybe converting the current layout into a
two-column table)?:

    Pandunia: a b c  d e f g h i j  k  l m n o p  r s t  u w x y z
    IPA:     [a b tʃ d e f g h i dʒ kʰ l m n o pʰ r s tʰ u w ʃ j z]
             [               x                                    ]

I think also "r" has allophones, right?

That would help making further explanations shorter, if needed.

> Are Spanish speaking people in Latin America familiar with Catalan and
> Galician?

I hope so :) Catalans and Galicians played important roles in the
Americas... But, of course, those pronunciation examples were intended
mainly for the rest of the Spaniards.

Anyway, I'll simplify the explanations.

-- 
Marcos Cruz
http://programandala.net

**Pull request closed without merging**
